language: php
sudo: false
php:
  - 7.2
  - nigthly

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update
  
install:
  - travis_retry composer update --prefer-dist
  
cache:
  directories:
    - $HOME/.composer/cache