language: php
sudo: false
php:
  - 7.2
  - nigthly

before_install:
  - composer self-update
  - composer clear-cache
  
install:
  - travis_retry composer update
  
cache:
  directories:
    - $HOME/.composer/cache
    
notifications:
  email: false