language: php
sudo: false
php:
  - 7.2
  - master
  
matrix:
  allow_failures:
    - php: master
  fast_finish: true
  
before_install:
  - composer self-update
  - composer clear-cache
  
install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader
  
script:
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep "Fatal error"; then exit 1; fi
  
cache:
  directories:
    - $HOME/.composer/cache
    
notifications:
  email: false