<?php
declare(strict_types=1);

namespace RouteCMS\Builder\Content\Input;

use RouteCMS\Builder\Content\DefaultContent;

/**
 * @author        Olaf Braun <info@braun-development.de>
 * @copyright     2013-2018 Olaf Braun - Software Development
 * @license       GNU Lesser General Public License <https://opensource.org/licenses/LGPL-3.0>
 */
class DefaultInput extends DefaultContent implements FormElement
{

	/**
	 * @var string
	 */
	protected $type = FormTypes::TEXT;

	/**
	 * @var string
	 */
	protected $value = "";

	/**
	 * DefaultInput constructor.
	 *
	 * @param string $value
	 * @param string $type
	 */
	public function __construct(string $value, string $type)
	{
		if (!empty($type)) $this->type = $type;
		parent::__construct("input");
		$this->value = $value;
	}

	/**
	 * @inheritDoc
	 */
	public function getHtml(): string
	{
		//update value on property list, because they don´t able to overwrite
		$this->addPropertyValue("value", $this->getValue());
		$this->addPropertyValue("type", $this->type);
		return parent::getHtml(); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
	public function getValue(): string
	{
		return $this->value;
	}

	/**
	 * @inheritdoc
	 */
	public function getContent(): string
	{
		return "";
	}
}